enum AuditActionType {
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  NFC_VERIFICATION_SUCCESS,
  NFC_VERIFICATION_FAILED,
  ABSENCE_REQUEST_CREATED,
  ABSENCE_REQUEST_CANCELLED,
  ABSENCE_REQUEST_APPROVED,
  ABSENCE_REQUEST_REJECTED,
  USER_CREATED,
  ROLE_ASSIGNED,
  ROLE_REMOVED,
  NFC_TOKEN_REGISTERED,
  NFC_TOKEN_REVOKED
}